version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: voicechat-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - ./backend/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"  

  frontend:
    build:
      context: ./frontend
    container_name: voicechat-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true    
    depends_on:
      - backend

volumes:
  node_modules:    